language: shell
cache: pip

matrix:
  include:      
    # - name: "Python 3.7 on macOS 10.14"
    #   os: osx
    #   osx_image: xcode11.3
    #   language: generic
    #   env:
    #     - export PATH="/usr/local/opt/flex/bin:$PATH"
    #     - export LDFLAGS="-L/usr/local/opt/flex/lib:$LDFLAGS"
    #     - export CPPFLAGS="-I/usr/local/opt/flex/include:$CPPFLAGS"
    #     - export PATH="/usr/local/opt/bison/bin:$PATH"
    #     - export LDFLAGS="-L/usr/local/opt/bison/lib:$LDFLAGS"

    - name: "Python 3.7 on xenial"
      os: linux
      dist: xenial
      sudo: required
      language: python
      python: 3.7

before_install:
  # Link gcc-7 and g++-7 to their standard commands
  - ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-7 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  - python3 -m pip install -U pip
  - python3 -m pip install -U pytest
  - python3 -m pip install -U qxelarator
  - python3 --version
  - pip3 --version
  - while sleep 5m; do echo "=====[ $SECONDS seconds, OpenQL still building... ]====="; done &


install:
  - cd deps
  - git clone https://github.com/imranashraf/travis-libqasm.git
  - cd travis-libqasm
  - python3 -m pip install . 
  - cd ..
  - git clone https://github.com/imranashraf/travis-eQASM_Assembler.git
  - cd travis-eQASM_Assembler/qisa-as
  - python3 -m pip install . 
  - cd ../../../.
  - python3 -m pip install . 
script:
  - python3 -m pytest



addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - swig
      - flex
      - bison
  homebrew:
    packages:
      - python3
      - cmake
      - swig
      - flex
      - bison
    update: true
